config/routes.rb
Distinct::Application.routes.draw do
  devise_for :representatives
  devise_for :technicians

  namespace :admin do
    resources :template_actions do
      get :autocomplete_admin_tolerance_action_message, on: :collection
    end
  end
  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config
  
  devise_for :representatives
  authenticated :representative do
    namespace :installed_base do
      resources :clients
      resources :installations
    end
  end
  match :installed_base, to: 'pages#landing'
  
  devise_for :technicians
  authenticated :technician do
    namespace :lab do
      post :update_plus_version
      resources :lots do
        resources :lot_versions do
          get :show_results
        end
      end
    end
  end
  match :lab, to: 'pages#landing'
  
  root :to => 'pages#landing', :as => :home
  
end

app/models/lot.rb
class Lot < ActiveRecord::Base
  attr_accessible :lot_number, :comments, :item_master_id
  attr_accessible :lot_versions_attributes
  
  belongs_to :item_master
  has_many :lot_versions, dependent: :destroy, order: :version
  accepts_nested_attributes_for :lot_versions, allow_destroy: true
  
  validates :item_master_id, presence: true
  validates :lot_number, presence: true, uniqueness: true
  
  before_validation :standardize
  
  def build_new_version(technician_id)
    lv = self.lot_versions.build(technician_id)
    lv.prepare_samples(self.item_master.test_suite)
  end
  
  # Retrieve the most recent sample for a given standard
  def last_sample(standard_id)
    Sample.joins("join lot_versions on samples.lot_version_id = lot_versions.id").where("lot_versions.lot_id = ? and samples.standard_id = ?", self.id, standard_id).order("samples.id DESC").limit(1).first
  end
  
  def passed?
    (self.lot_versions.present? && self.lot_versions.last.passed?)
  end
  
  private
  
  def standardize
    self.lot_number = self.lot_number.upcase if self.lot_number
  end
  
end

app/controllers/lab/base_controller.rb
class Lab::BaseController < ApplicationController
  before_filter :authenticate_technician!
  
end

app/controllers/lab/lot_versions_controller.rb
class Lab::LotVersionsController < Lab::BaseController
  before_filter :find_lot
  
  def new
    @lot_version = @lot.lot_versions.build(technician_id: current_technician.id)
    @lot_version.issue_version_number
    test_suite = @lot.item_master.test_suite
    if test_suite
      @lot_version.prepare_samples(test_suite)
    else
      redirect_to edit_lab_lot_path(@lot), flash: {error: "There is no test suite for item master #{@lot.item_master.code}!"}
      return
    end
  end
  
  def create
    @lot_version = @lot.lot_versions.build(params[:lot_version].merge({technician_id: current_technician.id}))
    if @lot_version.save
      stamp_data_version(@lot_version, params[:stamp_row])
      redirect_to edit_lab_lot_path(@lot), flash: {success: "Lot version ##{@lot_version.version} updated."}
    else
      render :new
    end
  end
  
  def edit
    @lot_version = LotVersion.find(params[:id])
  end
  
  def update
    @lot_version = LotVersion.find(params[:id])
    if @lot_version.update_attributes(params[:lot_version].merge({technician_id: current_technician.id}))
      stamp_data_version(@lot_version, params[:stamp_row])
      redirect_to edit_lab_lot_path(@lot), flash: {success: "Lot version ##{@lot_version.version} updated."}
    else
      render :edit
    end
  end
  
  def destroy
    @lot_version = LotVersion.find(params[:id])
    @lot_version.destroy
    
    redirect_to edit_lab_lot_path(@lot)
  end
  
  def show_results
    @lot_version = LotVersion.find(params[:lot_version_id])
  end
  
  private
  
  def find_lot
    @lot = Lot.find(params[:lot_id])
  end
  
  def stamp_data_version(lot_version, list)
    list.each do |key, value|
      if value.present?
        if value == '0'
          lot_version.samples[key.to_i].stamp_data_version!
        else
          sample = Sample.find(value)
          sample.stamp_data_version!
        end
      end
    end
  end
  
end

app/controllers/lab/lots_controller.rb
class Lab::LotsController < Lab::BaseController
  
  before_filter :find_lot, except: [:index, :new, :create]
  
  def index
    @lots = Lot.order('created_at desc').page(params[:page]).per(10)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @lots }
    end  
  end
  
  def show

  end
  
  def new
    @lot = Lot.new
   end
  
  def create
    @lot = Lot.new(params[:lot])
    if @lot.save
      redirect_to new_lab_lot_lot_version_path(@lot), flash: {success: "Lot ##{@lot.id} added."}
    else
      render :new
    end    
  end
  
  def edit

  end
  
  def update
    if @lot.update_attributes(params[:lot])
      redirect_to new_lab_lot_lot_version_path(@lot), flash: {success: 'Lot was successfully updated.'}
    else
      render :edit
    end
  end
  
  def update_plus_version
    if @lot.update_attributes(params[:lot])
      redirect_to lab_lot_path(@lot), flash: {success: 'Lot was successfully updated.'}
    else
      render :edit
    end
  end
  
  def destroy
    @lot.destroy
    
    redirect_to lab_lots_path
  end
  
  private
  
  def find_lot
    @lot = Lot.find(params[:id])
  end
  
end

app/helpers/lot_helper.rb
module LotHelper
  
  def result_class(sample)
    if sample.within_tolerance?
      'success'
    elsif sample.failed?
      'error'
    else
      'warning'
    end
  end
  
  def tolerance(standard)
    "[#{standard.min_tolerance} : #{standard.max_tolerance}]"
  end
  
end

app/views/lab/lots/_current_version.html.haml
%h4.text-info= "Version #{current_version.version} results"
%table.table.table-condensed
  %thead
    %tr
      %th Property
      %th Results from
      %th Tolerance
      %th Reading
      %th Pass
      %th Equipment
      %th Comment
  %tbody
    - current_version.samples.each do |sample|
      %tr{class: result_class(sample)}
        %td= sample.standard_property
        %td= sample.data_version.try(:version)
        %td= tolerance sample.standard
        %td= sample.value ? "#{sample.value} #{sample.unit_of_measure}" : ""
        %td= check_box_tag :pass, '1', sample.pass, disabled: true
        %td= sample.equipment.name 
        %td= sample.comments

app/views/lab/lots/_form.html.haml
= simple_form_for @lot, url: url, html: { class: "form-horizontal" } do |f|

  = f.input :lot_number, input_html: {class: 'input-mini'}, autofocus: true
  = f.association :item_master, collection: ItemMaster.active.map {|o| [o.code_description, o.id]}, input_html: {class: 'span6'}
  = f.input :comments, input_html: {class: 'span12'}, placeholder: 'Brief notes ...'
  
  .links
    -if @lot.persisted?
      - if @lot.lot_versions.count > 0
        = render partial: 'lot_versions'

  .form-actions
    -if @lot.persisted?
      %p.muted.pull-right
        %em
          = @lot.item_master.has_test_suite? ? "#{@lot.item_master.code} uses test suite #{@lot.item_master.test_suite.name} with #{@lot.item_master.test_suite.test_standards.count} tests." : ''
      = f.submit "Add a version", url: lab_update_plus_version_path(@lot), class: 'btn  btn-primary'
      = f.submit 'Update lot header', :class => "btn"
    -else
      = f.submit 'Add', :class => "btn btn-primary"

  - if @lot.lot_versions.last
    #show-results
      = render partial: 'current_version', object: @lot.lot_versions.last
    

app/views/lab/lots/_lot.html.haml
%tr
  %td= link_to lot.lot_number, lab_lot_path(lot)
  %td= lot.item_master.code
  %td= lot.item_master.description
  %td= lot.created_at.strftime('%Y/%m/%d %H:%M')
  %td{style: 'text-align: right;'}= zero_blank lot.lot_versions.count
  %td= check_box_tag :pass, '1', lot.passed?, disabled: true
  %td
    =link_to "Edit", edit_lab_lot_path(lot), class: 'btn btn-mini'
    =link_to "Delete", lab_lot_path(lot), method: :delete, confirm: "Really delete?", class: 'btn btn-mini btn-danger'

app/views/lab/lots/_lot_version.html.haml
%tr
  %td= lot_version.version
  %td= lot_version.updated_at.strftime('%Y/%m/%d %H:%M')
  %td= t('lot_version.status', passed: lot_version.samples.passed.count, samples: lot_version.samples.count)
  %td= lot_version.comments
  %td
    = link_to "Show", '#', class: 'btn btn-mini btn-info show-results', data: {lot_id: lot_version.lot_id, lot_version_id: lot_version.id}
    = link_to "Edit", edit_lab_lot_lot_version_path(@lot, lot_version), class: 'btn btn-mini'
    - if lot_version.eql? @lot.lot_versions.last
      =link_to "Delete", lab_lot_lot_version_path(@lot, lot_version), method: :delete, confirm: "Really delete?", class: 'btn btn-mini btn-danger'

app/views/lab/lots/_lot_versions.html.haml
%table.table.table-condensed
  %thead
    %tr
      %th.span1 Version
      %th.span2 Updated
      %th.span1 Status
      %th.span4 Comment
      %th.span2 Actions
  %tbody
    = render partial: 'lot_version', collection: @lot.lot_versions
    

app/views/lab/lots/edit.html.haml
.row.span11
  %h3.section-header Edit Lot ##{@lot.id}
  = render partial: 'form', locals: {url: lab_lot_path(@lot)}

app/views/lab/lots/index.html.haml
.row.span11
  %h3.section-header Lots
  %table.table.table-striped
    %thead
      %tr
        %th.span1 Number
        %th Item
        %th Description
        %th Date
        %th.span1 Versions
        %th.span1 Passed
        %th Actions
    %tbody
      = render partial: 'lot', collection: @lots
    = paginate @lots, :theme => 'twitter-bootstrap'     

app/views/lab/lots/new.html.haml
.row.span11
  %h3.section-header New Lot
  = render partial: 'form', locals: {url: lab_lots_path}

app/views/lab/lots/show.html.haml
.row.span10
  %h2.section-header
    %span.pull-right= @lot.created_at.strftime('%Y/%m/%d %H:%M')
    = "#{@lot.lot_number} : #{@lot.item_master.code} - #{@lot.item_master.description}"
  - @lot.lot_versions.each do |lot_version|  
    %h4.text-info
      %span.pull-right= lot_version.updated_at.strftime('%Y/%m/%d %H:%M')
      = "#{lot_version.version} : #{lot_version.comments}"
    %table.table
      %thead
        %tr
          %th.span2 Property
          %th.span2 Results from
          %th.span1 Tolerance
          %th.span1 Reading
          %th.span1 Pass
          %th.span2 Equipment
          %th.span2 Comment
      %tbody
      - lot_version.samples.each do |sample|
        %tr{class: result_class(sample)}
          %td= sample.standard_property
          %td= sample.data_version ? "version ##{sample.data_version_id}" : ''
          %td= tolerance sample.standard
          %td= "#{sample.value} #{sample.unit_of_measure}"
          %td= check_box_tag :pass, '1', sample.pass, disabled: true
          %td= sample.equipment.name
          %td= sample.comments
      

  