config/routes.rb
Distinct::Application.routes.draw do
  devise_for :representatives
  devise_for :technicians

  namespace :admin do
    resources :template_actions do
      get :autocomplete_admin_tolerance_action_message, on: :collection
    end
  end
  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config
  
  devise_for :representatives
  authenticated :representative do
    namespace :installed_base do
      resources :clients
      resources :installations
    end
  end
  match :installed_base, to: 'pages#landing'
  
  devise_for :technicians
  authenticated :technician do
    namespace :lab do
      post :update_plus_version
      resources :lots do
        resources :lot_versions do
          get :show_results
        end
      end
    end
  end
  match :lab, to: 'pages#landing'
  
  root :to => 'pages#landing', :as => :home
  
end

app/views/shared/_errors.html.haml
.alert.alert-error.fade.in
  %a.close{'data-dismiss' => "alert", href: "#"} &times;
  = f.error_notification
  %dl.dl-horizontal
    - object.errors.messages.each_pair do |key, value|
      %dt= object.class.human_attribute_name(key)
      %dd= value

app/views/shared/_flash.html.haml
#flash
  - if flash
    - flash.each do |kind, message|
      - message = render_flash_message(message)
      - if kind == :success
        .alert.alert-success
          =link_to raw("&times"), "#", class: "close", "data-dismiss"=>"alert"
          %p= message
      - if kind == :notice
        .alert.alert-info
          =link_to raw("&times"), "#", class: "close", "data-dismiss"=>"alert"
          %p= message
      - if kind == :alert
        .alert
          =link_to raw("&times"), "#", class: "close", "data-dismiss"=>"alert"
          %p= message
      - if kind == :error
        .alert.alert-error
          =link_to raw("&times"), "#", class: "close", "data-dismiss"=>"alert"
          %p= message

app/views/shared/_footer.html.erb
<div class="row-fluid footer">
	<div class="span2" style="line-height: 35px;">
		<span class="muted"><small><%= "#{APP_VERSION}" %></small></span>
	</div>
	<div class="span8" style="line-height: 35px;">
		<span class="pull-right">
			Website developed by <a href="http://mvesolutions.com" target="_blank" >MVE Solutions Inc.</a>
			<%= image_tag("solutions.logo.gif", :style => "height: 19px; padding-bottom: 5px;", :alt => "MVE Solutions Stylized Acorn Logo") %>
		</span>
	</div>
</div>

app/views/shared/_navbar.html.haml
.navbar.navbar-fixed-top
  .navbar-inner
    .container
      %a.btn.btn-navbar{'data-toggle' => "collapse", 'data-target' => ".nav-collapse"}
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      = link_to I18n.t('company.name'), :home, :class => "brand span2"
      = render partial: 'installed_base/shared/navmenu'
      = render partial: 'lab/shared/navmenu'
      -# Keep the style for spacing
      .nav.pull-right.btn-group{style: "margin-top: 7px;"}
        = link_to t('session.signin.label'), "#", :class => "btn btn-inverse"
        %a.btn.btn-inverse.dropdown-toggle{'data-toggle' => "dropdown", href: "#"}
          %span.caret
        %ul.dropdown-menu
          - if representative_signed_in?
            %li= link_to t('session.signout.representative'), destroy_representative_session_path, :method => :delete
          - else
            %li= link_to t('session.signin.representative'), new_representative_session_path
          - if technician_signed_in?
            %li= link_to t('session.signout.lab'), destroy_technician_session_path, :method => :delete
          - else
            %li= link_to t('session.signin.lab'), new_technician_session_path
          %li= link_to t('session.signin.admin'), '/admin/login'

app/views/shared/_sidebar.html.haml
.span2
  = link_to image_tag("logo.png", :alt => "Vera InkJet Stylized Color", class: 'vgap'), I18n.t('company.url')
  = render :partial => "shared/flash", :locals => { :flash => flash }
  = yield :sidebar