config/routes.rb
Distinct::Application.routes.draw do
  devise_for :representatives
  devise_for :technicians

  namespace :admin do
    resources :template_actions do
      get :autocomplete_admin_tolerance_action_message, on: :collection
    end
  end
  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config
  
  devise_for :representatives
  authenticated :representative do
    namespace :installed_base do
      resources :clients
      resources :installations
    end
  end
  match :installed_base, to: 'pages#landing'
  
  devise_for :technicians
  authenticated :technician do
    namespace :lab do
      post :update_plus_version
      resources :lots do
        resources :lot_versions do
          get :show_results
        end
      end
    end
  end
  match :lab, to: 'pages#landing'
  
  root :to => 'pages#landing', :as => :home
  
end

app/models/client.rb
class Client < ActiveRecord::Base
  
  attr_accessible :code, :name
  
  has_many :installations
  
  validates :code, presence: true, uniqueness: true
  validates :name, presence: true
  
  before_validation :standardize
  
  private
  
  def standardize
    self.code = self.code.upcase if self.code.present?
  end
  
end

app/controllers/installed_base/base_controller.rb
class InstalledBase::BaseController < ApplicationController
  before_filter :authenticate_representative!
  
  layout 'installed_base'
  
end

app/controllers/installed_base/clients_controller.rb
class InstalledBase::ClientsController < InstalledBase::BaseController
  
  before_filter :find_client, except: [:index, :new, :create]
  
  def index
    @clients = Client.order(:code).page(params[:page]).per(10)
  end
  
  def show
  end
  
  def new
    @client = Client.new
  end
  
  def create
    @client = Client.new(params[:client])
    if @client.save
      redirect_to installed_base_clients_path, flash: {success: "Client ##{@client.id} added."}
    else
      render :new
    end    
  end
  
  def edit
  end
  
  def update
    if @client.update_attributes(params[:client])
      redirect_to installed_base_clients_path, flash: {success: 'Client was successfully updated.'}
    else
      render :edit
    end
  end
  
  def destroy
    @client.destroy
    
    redirect_to installed_base_clients_path
  end
  
  private
  
  def find_client
    @client = Client.find(params[:id])
  end
  
end

app/controllers/installed_base/installations_controller.rb
class InstalledBase::InstallationsController < InstalledBase::BaseController
  
  before_filter :find_installation, except: [:index, :new, :create]
  
  def index
    respond_to do |format|
      format.html 
        @installations = Installation.order(:client_id, :location).page(params[:page]).per(10)
      format.csv { send_data Installation.to_csv, filename: "installations.csv" }
    end
  end
  
  def show
  end
  
  def new
    @installation = Installation.new
  end
  
  def create
    @installation = Installation.new(params[:installation])
    if @installation.save
      redirect_to installed_base_installations_path, flash: {success: "Installation ##{@installation.id} added."}
    else
      render :new
    end    
  end
  
  def edit
  end
  
  def update
    if @installation.update_attributes(params[:installation])
      redirect_to installed_base_installations_path, flash: {success: 'Installation was successfully updated.'}
    else
      render :edit
    end
  end
  
  def destroy
    @installation.destroy
    
    redirect_to installed_base_installations_path
  end
  
  private
  
  def find_installation
    @installation = Installation.find(params[:id])
  end
end

app/views/installed_base/clients/_client.html.haml
%tr
  %td= link_to client.code, installed_base_client_path(client)
  %td= client.name
  %td
    =link_to "Edit", edit_installed_base_client_path(client), class: 'btn btn-mini'
    =link_to "Delete", installed_base_client_path(client), method: :delete, confirm: "Really delete?", class: 'btn btn-mini btn-danger'

app/views/installed_base/clients/_form.html.haml
= simple_form_for @client, url: url, html: { class: "form-horizontal" } do |f|
  
  - if f.error_notification
    = render :partial => 'shared/errors', :locals => {:f => f, :object => @client}
    
  = f.input :code, input_html: {class: 'input-small'}, autofocus: true
  = f.input :name, input_html: {class: 'span4'}
  
  .form-actions
    -if @client.persisted?
      = f.submit 'Update client', :class => "btn"
    -else
      = f.submit 'Add', :class => "btn btn-primary"

app/views/installed_base/clients/edit.html.haml
.row
  %h3.section-header Edit Client
  = render partial: 'form', locals: {url: installed_base_client_path(@client)}

app/views/installed_base/clients/index.html.haml
.row
  %h3.section-header Clients
  %table.table.table-striped
    %thead
      %tr
        %th.span2 Code
        %th.span4 Name
        %th Actions
    %tbody
      = render partial: 'client', collection: @clients
    = paginate @clients, :theme => 'twitter-bootstrap'

app/views/installed_base/clients/new.html.haml
.row
  %h3.section-header New Client
  = render partial: 'form', locals: {url: installed_base_clients_path}

app/views/installed_base/clients/show.html.haml
.row
  %h2.section-header= @client.name
  
  %p
    %span.span2
      = label_tag :code
    %span.span10
      = text_field_tag :code, @client.code, readonly: true, class: 'span2'
  %p
    %span.span2
      = label_tag :name
    %span.span10  
      = text_field_tag :name, @client.name, readonly: true, class: 'span8'
  
  %h3 Printers
  %table.table.table-condensed
    %thead
      %tr
        %th Printer
        %th Ink System
        %th Consumption
        %th Function
        %th Location
        %th Installed
    %tbody
      - @client.installations.each do |installation|
        %tr
          %td= link_to installation.printer_model_name, installed_base_installation_path(installation)
          %td= installation.ink_system_name
          %td= installation.consumption_profile.code
          %td= installation.printer_function_name
          %td= installation.location
          %td= installation.installed_date.strftime('%Y/%m/%d')
  
          