config/routes.rb
Distinct::Application.routes.draw do
  devise_for :representatives
  devise_for :technicians

  namespace :admin do
    resources :template_actions do
      get :autocomplete_admin_tolerance_action_message, on: :collection
    end
  end
  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config
  
  devise_for :representatives
  authenticated :representative do
    namespace :installed_base do
      resources :clients
      resources :installations
    end
  end
  match :installed_base, to: 'pages#landing'
  
  devise_for :technicians
  authenticated :technician do
    namespace :lab do
      post :update_plus_version
      resources :lots do
        resources :lot_versions do
          get :show_results
        end
      end
    end
  end
  match :lab, to: 'pages#landing'
  
  root :to => 'pages#landing', :as => :home
  
end

app/models/installation.rb
require 'csv'

class Installation < ActiveRecord::Base
  
  attr_accessible :location, :installed_date
  attr_accessible :client_id, :representative_id, :printer_model_id, :ink_system_id, :consumption_profile_id, :printer_function_id
  
  belongs_to :client
  belongs_to :printer_model
  belongs_to :ink_system
  belongs_to :consumption_profile
  belongs_to :printer_function
  belongs_to :representative
  
  validates :client_id, presence: true
  validates :representative_id, presence: true
  validates :printer_model_id, presence: true
  validates :ink_system_id, presence: true
  validates :consumption_profile_id, presence: true
  validates :printer_function_id, presence: true
  validates :location, presence: true
  validates :installed_date, presence: true
  
  delegate :code, :name, to: :client, prefix: true
  delegate :name, to: :representative, prefix: true
  delegate :name, to: :printer_model, prefix: true
  delegate :name, to: :ink_system, prefix: true
  delegate :code, :name, to: :consumption_profile, prefix: true
  delegate :name, to: :printer_function, prefix: true
  
  def self.csv_columns
    [:client_code, :client_name, :printer_model_name, :ink_system_name, :consumption_profile_code, :printer_function_name, :representative_name, :location, :installed_date]
  end
  
  def self.import_csv(file)
    col = self.csv_columns
    results = []
    indx = 0
    CSV.parse(file, headers: true) do |row|
      indx += 1
      message = nil
      col.each_with_index do |field, indx|
        message = "#{field} missing" if !row[indx]
      end
      if !message
        client_code = row[col.index(:client_code)]
        client = Client.find_by_code(client_code)
        if !client
          client = Client.new(code: client_code, name: row[col.index(:client_name)])
          message = client.errrors.full_messages.join(', ') if !client.save
        end
      end
      if !message
        printer_model = PrinterModel.find_or_create_by_name(row[col.index(:printer_model_name)])
        ink_system = InkSystem.find_or_create_by_name(row[col.index(:ink_system_name)])
        consumption_profile = ConsumptionProfile.find_or_create_by_code(row[col.index(:consumption_profile_code)])
        printer_function = PrinterFunction.find_or_create_by_name(row[col.index(:printer_function_name)])
        names = row[col.index(:representative_name)].split(' ')
        first_name = names[0]
        last_name = names.drop(1).join(' ')
        representative = Representative.where("first_name = ? and last_name = ?", first_name, last_name).first
        message = "Representative #{first_name} #{last_name} required" if !representative
        installed_date = Date.parse(row[col.index(:installed_date)])
        if !message
          installation = Installation.new(
            client_id: client.id,
            printer_model_id: printer_model.id,
            ink_system_id: ink_system.id,
            consumption_profile_id: consumption_profile.id,
            printer_function_id: printer_function.id,
            representative_id: representative.id,
            location: row[col.index(:location)],
            installed_date: installed_date
            )
          if installation.save
            message = "Installation added"
          else
            message = installation.errors.full_messages.join(', ')
          end
        end
      end
      results << [indx, message, row.to_s]
    end
    results
  end
  
  def self.to_csv
    CSV.generate do |csv|
      csv << self.csv_columns
      self.order(:client_id, :location).each do |installation|
        csv << [
          installation.client_code,
          installation.client_name,
          installation.printer_model_name,
          installation.ink_system_name, 
          installation.consumption_profile_code, 
          installation.printer_function_name,
          installation.representative_name,
          installation.location,
          installation.installed_date.strftime('%Y%m%d')
          ]
      end
    end
  end
  
end

app/controllers/installed_base/base_controller.rb
class InstalledBase::BaseController < ApplicationController
  before_filter :authenticate_representative!
  
  layout 'installed_base'
  
end

app/controllers/installed_base/clients_controller.rb
class InstalledBase::ClientsController < InstalledBase::BaseController
  
  before_filter :find_client, except: [:index, :new, :create]
  
  def index
    @clients = Client.order(:code).page(params[:page]).per(10)
  end
  
  def show
  end
  
  def new
    @client = Client.new
  end
  
  def create
    @client = Client.new(params[:client])
    if @client.save
      redirect_to installed_base_clients_path, flash: {success: "Client ##{@client.id} added."}
    else
      render :new
    end    
  end
  
  def edit
  end
  
  def update
    if @client.update_attributes(params[:client])
      redirect_to installed_base_clients_path, flash: {success: 'Client was successfully updated.'}
    else
      render :edit
    end
  end
  
  def destroy
    @client.destroy
    
    redirect_to installed_base_clients_path
  end
  
  private
  
  def find_client
    @client = Client.find(params[:id])
  end
  
end

app/controllers/installed_base/installations_controller.rb
class InstalledBase::InstallationsController < InstalledBase::BaseController
  
  before_filter :find_installation, except: [:index, :new, :create]
  
  def index
    respond_to do |format|
      format.html 
        @installations = Installation.order(:client_id, :location).page(params[:page]).per(10)
      format.csv { send_data Installation.to_csv, filename: "installations.csv" }
    end
  end
  
  def show
  end
  
  def new
    @installation = Installation.new
  end
  
  def create
    @installation = Installation.new(params[:installation])
    if @installation.save
      redirect_to installed_base_installations_path, flash: {success: "Installation ##{@installation.id} added."}
    else
      render :new
    end    
  end
  
  def edit
  end
  
  def update
    if @installation.update_attributes(params[:installation])
      redirect_to installed_base_installations_path, flash: {success: 'Installation was successfully updated.'}
    else
      render :edit
    end
  end
  
  def destroy
    @installation.destroy
    
    redirect_to installed_base_installations_path
  end
  
  private
  
  def find_installation
    @installation = Installation.find(params[:id])
  end
end

app/views/installed_base/installations/_form.html.haml
= simple_form_for @installation, url: url, html: { class: "form-horizontal" } do |f|
  
  - if f.error_notification
    = render :partial => 'shared/errors', :locals => {:f => f, :object => @installation}
  
  = f.association :client, collection: Client.order(:code), input_html: {class: 'span6'}, autofocus: true
  = f.association :representative, collection: Representative.order(:last_name, :first_name).map{|o| [o.sort_name, o.id]}, input_html: {class: 'span4'}
  = f.association :printer_model, collection: PrinterModel.order(:name)
  = f.association :ink_system, collection: InkSystem.order(:name)
  = f.association :consumption_profile, collection: ConsumptionProfile.order(:code)
  = f.association :printer_function, collection: PrinterFunction.order(:name)
  = f.input :location, input_html: {class: 'span4'}
  = f.input :installed_date, as: :string, input_html: {type: 'text', class: 'span2', 'data-behaviour' => 'datepicker', 'data-date-format' => "yyyy-mm-dd"}
  
  .form-actions
    -if @installation.persisted?
      = f.submit 'Update installation', :class => "btn"
    -else
      = f.submit 'Add', :class => "btn btn-primary"

app/views/installed_base/installations/_installation.html.haml
%tr
  %td{title: installation.client_name}= link_to installation.client_code, installed_base_client_path(installation.client)
  %td= link_to installation.printer_model_name, installed_base_installation_path(installation)
  %td= installation.ink_system_name
  %td{title: installation.consumption_profile_name}= installation.consumption_profile.code
  %td= installation.printer_function_name
  %td= installation.representative_name
  %td
    =link_to "Edit", edit_installed_base_installation_path(installation), class: 'btn btn-mini'
    =link_to "Delete", installed_base_installation_path(installation), method: :delete, confirm: "Really delete?", class: 'btn btn-mini btn-danger'

app/views/installed_base/installations/edit.html.haml
.row
  %h3.section-header Edit Installation
  = render partial: 'form', locals: {url: installed_base_installation_path(@installation)}

app/views/installed_base/installations/index.html.haml
- content_for(:sidebar) do
  = link_to("Export to .csv", installed_base_installations_path(action: :index, format: :csv), class: 'btn btn-block btn-info')
  
.row
  %h3.section-header Installations
  %table.table.table-striped
    %thead
      %tr
        %th Client
        %th Printer
        %th Ink System
        %th Consumption
        %th Function
        %th Representative
        %th Actions
    %tbody
      = render partial: 'installation', collection: @installations
    = paginate @installations, :theme => 'twitter-bootstrap'

app/views/installed_base/installations/new.html.haml
.row
  %h3.section-header New Installation
  = render partial: 'form', locals: {url: installed_base_installations_path}

app/views/installed_base/installations/show.html.haml
.row
  %h2.section-header= "#{@installation.client_code} : #{@installation.printer_model_name}"
  
  %p
    %span.span2
      = label_tag :client
    %span.span10
      = text_field_tag :client, "#{@installation.client_code} - #{@installation.client_name}", readonly: true, class: 'span8'
  %p
    %span.span2
      = label_tag :representative_name
    %span.span10  
      = text_field_tag :representative_name, @installation.representative_name, readonly: true, class: 'span6'
  %p
    %span.span2
      = label_tag :printer_model_name
    %span.span10  
      = text_field_tag :printer_model_name, @installation.printer_model_name, readonly: true, class: 'span2'
  %p
    %span.span2
      = label_tag :ink_system_name
    %span.span10  
      = text_field_tag :ink_system_name, @installation.ink_system_name, readonly: true, class: 'span2'
  %p
    %span.span2
      = label_tag :consumption_profile
    %span.span10
      = text_field_tag :consumption_profile, "#{@installation.consumption_profile_code} - #{@installation.consumption_profile_name}", readonly: true, class: 'span6'
  %p
    %span.span2
      = label_tag :printer_function_name
    %span.span10  
      = text_field_tag :printer_function_name, @installation.printer_function_name, readonly: true, class: 'span2'
  %p
    %span.span2
      = label_tag :location
    %span.span10  
      = text_field_tag :location, @installation.location, readonly: true, class: 'span6'
  %p
    %span.span2
      = label_tag :installed_date
    %span.span10  
      = text_field_tag :installed_date, @installation.installed_date.strftime('%Y/%m/%d'), readonly: true, class: 'span2'